use crate::domain::ast::*;
use crate::CompileResult;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum CodegenError {
    #[error("Codegen error: {0}")]
    Generic(String),
}

pub struct CodeGenerator;

impl CodeGenerator {
    pub fn new() -> Self {
        CodeGenerator
    }

    pub fn generate(&mut self, program: &Program) -> Result<CompileResult, CodegenError> {
        let js = self.gen_js(program)?;
        let html = self.gen_html(program)?;
        Ok(CompileResult { html, js })
    }

    // ── JavaScript ───────────────────────────────────────────────────────────

    fn gen_js(&self, program: &Program) -> Result<String, CodegenError> {
        let mut out = String::new();
        out.push_str("// Generated by Nexa compiler\n\"use strict\";\n\n");
        out.push_str(RUNTIME);

        for decl in &program.declarations {
            if let Declaration::Class(cls) = decl {
                out.push_str(&self.gen_class(cls)?);
            }
        }

        out.push_str("\n// ── Routes ──────────────────────────────────────────────────\n");
        out.push_str("const _routes = {};\n");
        for route in &program.routes {
            out.push_str(&format!(
                "_routes['{}'] = () => new {}().render();\n",
                route.path, route.target
            ));
        }
        out.push_str(BOOT);
        Ok(out)
    }

    fn gen_class(&self, cls: &ClassDecl) -> Result<String, CodegenError> {
        let mut out = String::new();
        out.push_str(&format!("class {} {{\n", cls.name));

        if let Some(ctor) = &cls.constructor {
            let params: Vec<_> = ctor.params.iter().map(|p| p.name.as_str()).collect();
            out.push_str(&format!("  constructor({}) {{\n", params.join(", ")));
            for stmt in &ctor.body {
                out.push_str(&self.gen_stmt(stmt, 2)?);
            }
            out.push_str("  }\n\n");
        }

        for method in &cls.methods {
            let params: Vec<_> = method.params.iter().map(|p| p.name.as_str()).collect();
            out.push_str(&format!("  {}({}) {{\n", method.name, params.join(", ")));
            for stmt in &method.body {
                out.push_str(&self.gen_stmt(stmt, 2)?);
            }
            out.push_str("  }\n\n");
        }

        out.push_str("}\n\n");
        Ok(out)
    }

    /// Generate a statement with the given indentation level (in spaces).
    fn gen_stmt(&self, stmt: &Stmt, indent: usize) -> Result<String, CodegenError> {
        let pad = " ".repeat(indent * 2);
        let _inner_pad = " ".repeat((indent + 1) * 2);

        match stmt {
            Stmt::Return(None) => Ok(format!("{pad}return;\n")),
            Stmt::Return(Some(expr)) => Ok(format!("{pad}return {};\n", self.gen_expr(expr)?)),
            Stmt::Assign {
                object,
                field,
                value,
            } => {
                // this.field = x  or  local = x  (stored as field == name when object == Ident)
                let lhs = match object {
                    Expr::This => format!("this.{field}"),
                    Expr::Ident(n) if n == field => field.clone(),
                    other => format!("{}.{field}", self.gen_expr(other)?),
                };
                Ok(format!("{pad}{lhs} = {};\n", self.gen_expr(value)?))
            }
            Stmt::Let { name, init, .. } => {
                Ok(format!("{pad}let {name} = {};\n", self.gen_expr(init)?))
            }
            Stmt::If {
                cond,
                then_body,
                else_body,
            } => {
                let mut s = format!("{pad}if ({}) {{\n", self.gen_expr(cond)?);
                for st in then_body {
                    s.push_str(&self.gen_stmt(st, indent + 1)?);
                }
                if let Some(eb) = else_body {
                    s.push_str(&format!("{pad}}} else {{\n"));
                    for st in eb {
                        s.push_str(&self.gen_stmt(st, indent + 1)?);
                    }
                }
                s.push_str(&format!("{pad}}}\n"));
                Ok(s)
            }
            Stmt::While { cond, body } => {
                let mut s = format!("{pad}while ({}) {{\n", self.gen_expr(cond)?);
                for st in body {
                    s.push_str(&self.gen_stmt(st, indent + 1)?);
                }
                s.push_str(&format!("{pad}}}\n"));
                Ok(s)
            }
            Stmt::For { var, iter, body } => {
                let mut s = format!("{pad}for (const {var} of {}) {{\n", self.gen_expr(iter)?);
                for st in body {
                    s.push_str(&self.gen_stmt(st, indent + 1)?);
                }
                s.push_str(&format!("{pad}}}\n"));
                Ok(s)
            }
            Stmt::Break => Ok(format!("{pad}break;\n")),
            Stmt::Continue => Ok(format!("{pad}continue;\n")),
            Stmt::Expr(expr) => Ok(format!("{pad}{};\n", self.gen_expr(expr)?)),
        }
    }

    fn gen_expr(&self, expr: &Expr) -> Result<String, CodegenError> {
        match expr {
            Expr::StringLit(s) => Ok(format!(
                "\"{}\"",
                s.replace('\\', "\\\\").replace('"', "\\\"")
            )),
            Expr::IntLit(n) => Ok(n.to_string()),
            Expr::BoolLit(b) => Ok(b.to_string()),
            Expr::Ident(name) => Ok(name.clone()),
            Expr::This => Ok("this".into()),

            Expr::FieldAccess(obj, field) => Ok(format!("{}.{}", self.gen_expr(obj)?, field)),
            Expr::MethodCall {
                receiver,
                method,
                args,
            } => {
                let args_js: Result<Vec<_>, _> = args.iter().map(|a| self.gen_expr(a)).collect();
                Ok(format!(
                    "{}.{}({})",
                    self.gen_expr(receiver)?,
                    method,
                    args_js?.join(", ")
                ))
            }
            Expr::Call { callee, args } => {
                let args_js: Result<Vec<_>, _> = args.iter().map(|a| self.gen_expr(a)).collect();
                Ok(format!("{}({})", callee, args_js?.join(", ")))
            }
            Expr::Lambda { params, body } => {
                let p: Vec<_> = params.iter().map(|p| p.name.as_str()).collect();
                Ok(format!("({}) => {}", p.join(", "), self.gen_expr(body)?))
            }
            Expr::Block { tag, children } => {
                let kids: Result<Vec<_>, _> = children.iter().map(|c| self.gen_expr(c)).collect();
                Ok(format!("{}([{}])", tag, kids?.join(", ")))
            }
            Expr::Binary { op, left, right } => {
                let l = self.gen_expr(left)?;
                let r = self.gen_expr(right)?;
                Ok(format!("({} {} {})", l, op.as_js(), r))
            }
            Expr::Unary { op, expr } => {
                let inner = self.gen_expr(expr)?;
                let op_str = match op {
                    UnOp::Not => "!",
                    UnOp::Neg => "-",
                };
                Ok(format!("({op_str}{inner})"))
            }
        }
    }

    // ── HTML ─────────────────────────────────────────────────────────────────

    fn gen_html(&self, program: &Program) -> Result<String, CodegenError> {
        let title = &program.name;
        Ok(format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #0f0f13;
      color: #e2e2e8;
      min-height: 100vh;
    }}
    #app {{
      max-width: 960px;
      margin: 0 auto;
      padding: 2rem 1.5rem;
    }}
    .nx-page {{
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }}
    button {{
      background: #6c63ff;
      color: #fff;
      border: none;
      padding: 0.5rem 1.25rem;
      border-radius: 6px;
      cursor: pointer;
      font-size: 1rem;
      transition: background 0.15s;
    }}
    button:hover {{ background: #5a52d5; }}
  </style>
</head>
<body>
  <div id="app"></div>
  <script src="/app.js"></script>
</body>
</html>
"#
        ))
    }
}

impl Default for CodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

// ── Embedded JS runtime ───────────────────────────────────────────────────────

const RUNTIME: &str = r#"// ── Nexa Runtime ────────────────────────────────────────────────
function _appendAll(parent, items) {
  const arr = Array.isArray(items) ? items.flat(Infinity) : [items];
  arr.forEach(child => {
    if (child instanceof Node) parent.appendChild(child);
  });
}

function Text(content) {
  const el = document.createElement("span");
  el.textContent = String(content);
  return el;
}

function Column(children) {
  const el = document.createElement("div");
  el.style.cssText = "display:flex;flex-direction:column;gap:8px;";
  _appendAll(el, children);
  return el;
}

function Row(children) {
  const el = document.createElement("div");
  el.style.cssText = "display:flex;flex-direction:row;gap:8px;align-items:center;";
  _appendAll(el, children);
  return el;
}

function Page(children) {
  const el = document.createElement("main");
  el.className = "nx-page";
  _appendAll(el, children);
  return el;
}

function Button(label, onClick) {
  const el = document.createElement("button");
  el.textContent = String(label);
  if (typeof onClick === "function") el.addEventListener("click", onClick);
  return el;
}

function Input(placeholder, onChange) {
  const el = document.createElement("input");
  el.placeholder = String(placeholder ?? "");
  if (typeof onChange === "function") el.addEventListener("input", e => onChange(e.target.value));
  return el;
}

function Heading(text) {
  const el = document.createElement("h1");
  el.textContent = String(text);
  return el;
}

function Paragraph(text) {
  const el = document.createElement("p");
  el.textContent = String(text);
  return el;
}
// ─────────────────────────────────────────────────────────────────────────────

"#;

const BOOT: &str = r#"
// ── Boot ─────────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", () => {
  const path = window.location.pathname;
  const handler = _routes[path] ?? _routes["/"];
  if (handler) {
    const el = handler();
    if (el instanceof Node) document.getElementById("app").appendChild(el);
  }
});
"#;
