//! JavaScript backend for the Nexa IR.
//!
//! Pipeline: `Program` → `lower::lower()` → `IrModule` → this file → JS + HTML.
//!
//! The `CodeGenerator` is the JS backend. Future backends (WASM, native, …)
//! would implement their own pass over `IrModule` without touching this file.

use crate::application::services::lower;
use crate::domain::ast::Program;
use crate::domain::ir::*;
use crate::CompileResult;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum CodegenError {
    #[error("Codegen error: {0}")]
    Generic(String),
}

pub struct CodeGenerator;

impl CodeGenerator {
    pub fn new() -> Self {
        CodeGenerator
    }

    /// Entry point: lower the AST to IR, then emit JS + HTML.
    pub fn generate(&mut self, program: &Program) -> Result<CompileResult, CodegenError> {
        let ir = lower::lower(program);
        let js = self.emit_js(&ir)?;
        let html = self.emit_html(&ir);
        Ok(CompileResult { html, js })
    }

    // ── JavaScript emission ───────────────────────────────────────────────────

    fn emit_js(&self, ir: &IrModule) -> Result<String, CodegenError> {
        let mut out = String::new();
        out.push_str("// Generated by Nexa compiler\n\"use strict\";\n\n");
        out.push_str(RUNTIME);

        for cls in &ir.classes {
            out.push_str(&self.emit_class(cls)?);
        }

        out.push_str("\n// ── Routes ──────────────────────────────────────────────────\n");
        out.push_str("const _routes = {};\n");
        for route in &ir.routes {
            out.push_str(&format!(
                "_routes[\"{}\"] = () => new {}().render();\n",
                route.path, route.target
            ));
        }
        out.push_str(BOOT);
        Ok(out)
    }

    fn emit_class(&self, cls: &IrClass) -> Result<String, CodegenError> {
        let mut out = format!("class {} {{\n", cls.name);

        if !cls.constructor_params.is_empty() || !cls.constructor_body.is_empty() {
            let params: Vec<_> = cls.constructor_params.iter().map(|p| p.name.as_str()).collect();
            out.push_str(&format!("  constructor({}) {{\n", params.join(", ")));
            for stmt in &cls.constructor_body {
                out.push_str(&self.emit_stmt(stmt, 2)?);
            }
            out.push_str("  }\n\n");
        }

        for method in &cls.methods {
            let params: Vec<_> = method.params.iter().map(|p| p.name.as_str()).collect();
            let async_prefix = if method.is_async { "async " } else { "" };
            out.push_str(&format!(
                "  {}{}({}) {{\n",
                async_prefix,
                method.name,
                params.join(", ")
            ));
            for stmt in &method.body {
                out.push_str(&self.emit_stmt(stmt, 2)?);
            }
            out.push_str("  }\n\n");
        }

        out.push_str("}\n\n");
        Ok(out)
    }

    fn emit_stmt(&self, stmt: &IrStmt, indent: usize) -> Result<String, CodegenError> {
        let pad = "  ".repeat(indent);
        match stmt {
            IrStmt::Return(None) => Ok(format!("{pad}return;\n")),
            IrStmt::Return(Some(e)) => Ok(format!("{pad}return {};\n", self.emit_expr(e)?)),
            IrStmt::Assign { target, value } => {
                Ok(format!("{pad}{} = {};\n", self.emit_expr(target)?, self.emit_expr(value)?))
            }
            IrStmt::Let { name, init, .. } => {
                Ok(format!("{pad}let {name} = {};\n", self.emit_expr(init)?))
            }
            IrStmt::If { cond, then_body, else_body } => {
                let mut s = format!("{pad}if ({}) {{\n", self.emit_expr(cond)?);
                for st in then_body {
                    s.push_str(&self.emit_stmt(st, indent + 1)?);
                }
                if let Some(eb) = else_body {
                    s.push_str(&format!("{pad}}} else {{\n"));
                    for st in eb {
                        s.push_str(&self.emit_stmt(st, indent + 1)?);
                    }
                }
                s.push_str(&format!("{pad}}}\n"));
                Ok(s)
            }
            IrStmt::While { cond, body } => {
                let mut s = format!("{pad}while ({}) {{\n", self.emit_expr(cond)?);
                for st in body {
                    s.push_str(&self.emit_stmt(st, indent + 1)?);
                }
                s.push_str(&format!("{pad}}}\n"));
                Ok(s)
            }
            IrStmt::For { var, iter, body } => {
                let mut s = format!("{pad}for (const {var} of {}) {{\n", self.emit_expr(iter)?);
                for st in body {
                    s.push_str(&self.emit_stmt(st, indent + 1)?);
                }
                s.push_str(&format!("{pad}}}\n"));
                Ok(s)
            }
            IrStmt::Break => Ok(format!("{pad}break;\n")),
            IrStmt::Continue => Ok(format!("{pad}continue;\n")),
            IrStmt::Discard(e) => Ok(format!("{pad}{};\n", self.emit_expr(e)?)),
        }
    }

    fn emit_expr(&self, expr: &IrExpr) -> Result<String, CodegenError> {
        match expr {
            IrExpr::Str(s) => Ok(format!(
                "\"{}\"",
                s.replace('\\', "\\\\").replace('"', "\\\"")
            )),
            IrExpr::Int(n) => Ok(n.to_string()),
            IrExpr::Bool(b) => Ok(b.to_string()),
            IrExpr::Local(name) => Ok(name.clone()),
            IrExpr::SelfRef => Ok("this".into()),
            IrExpr::Field { receiver, name } => {
                Ok(format!("{}.{name}", self.emit_expr(receiver)?))
            }
            IrExpr::Call { receiver, method, args } => {
                let args_js = self.emit_exprs(args)?;
                Ok(format!("{}.{method}({args_js})", self.emit_expr(receiver)?))
            }
            IrExpr::Invoke { callee, args } => {
                let args_js = self.emit_exprs(args)?;
                Ok(format!("{callee}({args_js})"))
            }
            IrExpr::Closure { params, body } => {
                let ps: Vec<_> = params.iter().map(|p| p.name.as_str()).collect();
                Ok(format!("({}) => {}", ps.join(", "), self.emit_expr(body)?))
            }
            IrExpr::Node { tag, children } => {
                let kids = self.emit_exprs(children)?;
                Ok(format!("{tag}([{kids}])"))
            }
            IrExpr::Bin { op, lhs, rhs } => {
                let op_str = match op {
                    IrBinOp::Add => "+",  IrBinOp::Sub => "-",  IrBinOp::Mul => "*",
                    IrBinOp::Div => "/",  IrBinOp::Mod => "%",
                    IrBinOp::Eq  => "===",IrBinOp::Ne  => "!==",
                    IrBinOp::Lt  => "<",  IrBinOp::Gt  => ">",
                    IrBinOp::Le  => "<=", IrBinOp::Ge  => ">=",
                    IrBinOp::And => "&&", IrBinOp::Or  => "||",
                };
                Ok(format!("({} {op_str} {})", self.emit_expr(lhs)?, self.emit_expr(rhs)?))
            }
            IrExpr::Unary { op, operand } => {
                let op_str = match op { IrUnOp::Not => "!", IrUnOp::Neg => "-" };
                Ok(format!("({op_str}{})", self.emit_expr(operand)?))
            }
            IrExpr::Await(inner) => Ok(format!("(await {})", self.emit_expr(inner)?)),
            IrExpr::List(items) => {
                let parts = self.emit_exprs(items)?;
                Ok(format!("[{parts}]"))
            }
            IrExpr::DynamicImport(path) => Ok(format!("import(\"{path}\")")),
        }
    }

    fn emit_exprs(&self, exprs: &[IrExpr]) -> Result<String, CodegenError> {
        let parts: Result<Vec<_>, _> = exprs.iter().map(|e| self.emit_expr(e)).collect();
        Ok(parts?.join(", "))
    }

    // ── HTML emission ─────────────────────────────────────────────────────────

    fn emit_html(&self, ir: &IrModule) -> String {
        let title = &ir.name;
        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #0f0f13;
      color: #e2e2e8;
      min-height: 100vh;
    }}
    #app {{
      max-width: 960px;
      margin: 0 auto;
      padding: 2rem 1.5rem;
    }}
    .nx-page {{
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }}
    button {{
      background: #6c63ff;
      color: #fff;
      border: none;
      padding: 0.5rem 1.25rem;
      border-radius: 6px;
      cursor: pointer;
      font-size: 1rem;
      transition: background 0.15s;
    }}
    button:hover {{ background: #5a52d5; }}
  </style>
</head>
<body>
  <div id="app"></div>
  <script src="/app.js"></script>
</body>
</html>
"#
        )
    }
}

impl Default for CodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

// ── Embedded JS runtime ───────────────────────────────────────────────────────

const RUNTIME: &str = r#"// ── Nexa Runtime ────────────────────────────────────────────────
function _appendAll(parent, items) {
  const arr = Array.isArray(items) ? items.flat(Infinity) : [items];
  arr.forEach(child => {
    if (child instanceof Node) parent.appendChild(child);
  });
}

function Text(content) {
  const el = document.createElement("span");
  el.textContent = String(content);
  return el;
}

function Column(children) {
  const el = document.createElement("div");
  el.style.cssText = "display:flex;flex-direction:column;gap:8px;";
  _appendAll(el, children);
  return el;
}

function Row(children) {
  const el = document.createElement("div");
  el.style.cssText = "display:flex;flex-direction:row;gap:8px;align-items:center;";
  _appendAll(el, children);
  return el;
}

function Page(children) {
  const el = document.createElement("main");
  el.className = "nx-page";
  _appendAll(el, children);
  return el;
}

function Button(label, onClick) {
  const el = document.createElement("button");
  el.textContent = String(label);
  if (typeof onClick === "function") el.addEventListener("click", onClick);
  return el;
}

function Input(placeholder, onChange) {
  const el = document.createElement("input");
  el.placeholder = String(placeholder ?? "");
  if (typeof onChange === "function") el.addEventListener("input", e => onChange(e.target.value));
  return el;
}

function Heading(text) {
  const el = document.createElement("h1");
  el.textContent = String(text);
  return el;
}

function Paragraph(text) {
  const el = document.createElement("p");
  el.textContent = String(text);
  return el;
}

// ── List<T> runtime ───────────────────────────────────────────────
/**
 * _NexaList — generic list wrapper.
 * Exposes the typed API that Nexa List<T> methods compile to:
 *   push(item), pop(), get(i), length(), isEmpty(), contains(item),
 *   forEach(fn), map(fn), filter(fn), find(fn), slice(from,to)
 * The underlying storage is a plain JS array so V8 handles GC.
 */
class _NexaList {
  constructor(items = []) { this._data = Array.isArray(items) ? [...items] : [items]; }
  push(item)       { this._data.push(item); return this; }
  pop()            { return this._data.pop(); }
  get(i)           { return this._data[i]; }
  length()         { return this._data.length; }
  isEmpty()        { return this._data.length === 0; }
  contains(item)   { return this._data.includes(item); }
  forEach(fn)      { this._data.forEach(fn); }
  map(fn)          { return new _NexaList(this._data.map(fn)); }
  filter(fn)       { return new _NexaList(this._data.filter(fn)); }
  find(fn)         { return this._data.find(fn); }
  slice(from, to)  { return new _NexaList(this._data.slice(from, to)); }
  [Symbol.iterator]() { return this._data[Symbol.iterator](); }
  toArray()        { return [...this._data]; }
}
/** List(items...)  — constructor function matching Nexa syntax. */
function List(...items) { return new _NexaList(items); }

// ── Logger ────────────────────────────────────────────────────────
/** log(value, ...) — write to the browser console and an on-page log panel. */
function log(...args) {
  console.log(...args);
  let panel = document.getElementById("_nx_log");
  if (!panel) {
    panel = document.createElement("div");
    panel.id = "_nx_log";
    panel.style.cssText = [
      "position:fixed;bottom:0;left:0;right:0;max-height:200px;overflow-y:auto",
      "background:#0d0d0d;color:#a8ff78;font:12px/1.5 monospace",
      "padding:8px 12px;border-top:1px solid #333;z-index:9999",
    ].join(";");
    document.body.appendChild(panel);
  }
  const line = document.createElement("div");
  line.textContent = args.map(a =>
    typeof a === "object" ? JSON.stringify(a) : String(a)
  ).join(" ");
  panel.appendChild(line);
  panel.scrollTop = panel.scrollHeight;
}

"#;

const BOOT: &str = r#"
// ── Boot ─────────────────────────────────────────────────────────
(function() {
  const path = window.location.pathname;
  const handler = _routes[path] || _routes["/"];
  if (handler) {
    const root = document.getElementById("app");
    if (root) {
      const view = handler();
      if (view instanceof Node) root.appendChild(view);
    }
  }
})();
"#;
